feat: add windows notification when download complete
flybywiresim/installer pull request #115
Opened 2021-01-27 01:39 UTC by FoxtrotSierra6829

Fixes #79

## Summary of Changes
Windows Notification is displayed when the download and install process is completed.

## Screenshots (if necessary)
![Screenshot (1244)](https://user-images.githubusercontent.com/50082450/105929280-8bd70080-6047-11eb-95cd-ecac3d7c3720.png)

## Additional context
Currently there is no option to disable it, as considered in #79, but since it just goes away after some seconds (it's not permanent in notification center), I don't really see the need.
About the icon: there isn't really much we can do about it. It's using the partly transparent icon from the application and adds the windows theme color as a layer below it. Hopefully gets fixed in future Windows versions, just like in the start menu.

Discord username (if different from GitHub):
Foxtrot Sierra#6420

2021-01-27 13:14 UTC, FoxtrotSierra6829 commented
Merge after #116

2021-01-27 16:46 UTC, nistei requested changes

2021-01-27 16:46 UTC, nistei commented on src/renderer/components/AircraftSection/index.tsx
> +        });
Please add a `.catch` which just logs the error to console.

2021-01-28 03:11 UTC, nistei requested changes

2021-01-28 03:11 UTC, nistei commented on src/renderer/components/AircraftSection/index.tsx
> +        }
```suggestion
        Notification.requestPermission().then(function () {
            new Notification('Download complete!', {
                'body': "You're ready to fly",
            });
        }).catch(e => console.log(e));
```

2021-01-28 15:52 UTC, nistei approved these changes

2021-01-28 15:52 UTC, merged