feat: made reset button more clear of its purpose
flybywiresim/installer pull request #127
Opened 2021-02-05 20:22 UTC by ZigTag

Fixes #100 

## Summary of Changes

Made reset button more clear of its actions

## Screenshots (if necessary)

Before:
![image](https://user-images.githubusercontent.com/17077422/107085054-c447ae80-67ac-11eb-8f6e-f9db422f990d.png)
After:
![image](https://user-images.githubusercontent.com/17077422/107085017-b6922900-67ac-11eb-9091-4d3b140e1e0e.png)

2021-02-05 21:58 UTC, nistei requested changes

2021-02-05 21:58 UTC, nistei commented on src/renderer/components/GeneralSettings/styles.tsx
> +
Could probably make it a button now instead of h6

2021-02-05 22:11 UTC, FoxtrotSierra6829 requested changes

2021-02-05 22:11 UTC, FoxtrotSierra6829 commented on src/renderer/components/GeneralSettings/styles.tsx
> +  background: #fa3516;
`background: #fc3a3a;`
different red than the one suggested by Harry

2021-02-05 22:11 UTC, FoxtrotSierra6829 commented on src/renderer/components/GeneralSettings/styles.tsx
> +  border-color: #fa3516;
`border-color: #fc3a3a;`
different red than the one suggested by Harry

2021-02-05 22:11 UTC, FoxtrotSierra6829 commented on src/renderer/components/GeneralSettings/styles.tsx
> +    color: ${colors.mutedTextDark} !important;
the text remains white on the similar buttons while hovering

2021-02-06 04:07 UTC, nistei approved these changes

2021-02-06 04:07 UTC, merged