Branch descriptions
flybywiresim/installer pull request #135
Opened 2021-02-18 20:12 UTC by ZigTag

Fixes #67 

## Summary of Changes

## Screenshots (if necessary)

![image](https://user-images.githubusercontent.com/17077422/108415515-7f773b00-71e2-11eb-84d9-6e7344ab6c20.png)

## Additional context

Discord username (if different from GitHub):

2021-02-19 16:12 UTC, nistei commented
Should maybe change the heading to `Version Info` since we call them mainline and experimental versions.

2021-02-26 02:23 UTC, FoxtrotSierra6829 requested changes

2021-02-26 02:23 UTC, FoxtrotSierra6829 commented on src/renderer/components/App/index.tsx
> +                                        This branch is updated whenever the 'fbw' branch on Github is updated, which is around every 12 hours.
This branch -> this version

2021-02-26 02:23 UTC, FoxtrotSierra6829 commented on src/renderer/components/App/index.tsx
> +                                        This branch is updated whenever the 'autopilot' branch on Github is updated, which is around every 12 hours.
This branch -> this version

2021-02-28 22:57 UTC, Benjozork commented
I don't like the design of this, should maybe be a tooltip on the version ( with a ? icon or something)

2021-03-08 00:05 UTC, FoxtrotSierra6829 commented on src/renderer/components/App/index.tsx
> +                                        Stable is our variant that has the least bugs and best performance. This branch will not
```suggestion
                                        Stable is our variant that has the least bugs and best performance. This version will not
```

2021-03-08 00:05 UTC, FoxtrotSierra6829 commented on src/renderer/components/App/index.tsx
> +                                        Stable is our variant that has the least bugs and best performance. This branch will not
Sorry, found another

2021-03-08 21:45 UTC, FoxtrotSierra6829 approved these changes

2021-03-08 21:48 UTC, FoxtrotSierra6829 commented
Other than the concern of @Benjozork, LGTM

2021-03-13 20:13 UTC, merged