feat: automatically display changelog after update
flybywiresim/installer pull request #146
Opened 2021-03-04 13:12 UTC by FoxtrotSierra6829

Fixes #119 

## Summary of Changes
automatically display changelog after update

## Screenshots (if necessary)
![grafik](https://user-images.githubusercontent.com/50082450/109968943-9abe6c00-7cf3-11eb-8325-0bfb6cf7eaa5.png)

## Additional context

Discord username (if different from GitHub):
Foxtrot Sierra#6420

2021-03-04 20:02 UTC, ZigTag requested changes

2021-03-04 20:02 UTC, ZigTag commented on src/renderer/components/ChangelogModal/index.tsx
> +function versionchanged() {
`versionChanged`, also it should be a const function component `const versionChanged = () => {`

2021-03-04 22:59 UTC, ZigTag approved these changes
LGTM

2021-03-14 02:35 UTC, ZigTag reviewed
Lgtm

2021-03-14 02:35 UTC, ZigTag approved these changes
Lgtm

2021-03-16 23:08 UTC, nistei requested changes

2021-03-16 23:08 UTC, nistei commented on src/main/index.ts
> +
```suggestion
```

2021-03-16 23:28 UTC, nistei approved these changes
LGTM

2021-03-16 23:28 UTC, merged