fix: switch version
flybywiresim/installer pull request #151
Opened 2021-03-07 01:42 UTC by FoxtrotSierra6829

## Summary of Changes

- Do not allow version switching while download preparation
- Show Switch Version instead of Update

## Screenshots (if necessary)

![grafik](https://user-images.githubusercontent.com/50082450/110226355-c48fb280-7eee-11eb-935b-06c70c5946b2.png)

## Additional context

Discord username (if different from GitHub):
Foxtrot Sierra#6420

2021-03-08 21:34 UTC, ZigTag approved these changes

2021-03-08 22:22 UTC, nistei requested changes

2021-03-08 22:22 UTC, nistei commented on src/renderer/components/AircraftSection/index.tsx
> +            if (selectedTrack != installedTrack && installedTrack != null) {
```suggestion
            if (selectedTrack !== installedTrack && installedTrack !== null) {
```

2021-03-08 22:22 UTC, nistei commented on src/renderer/components/AircraftSection/index.tsx
> +        if (!isDownloading && installStatus != InstallStatus.DownloadPrep) {
```suggestion
        if (!isDownloading && installStatus !== InstallStatus.DownloadPrep) {
```

2021-03-08 22:22 UTC, nistei commented on src/renderer/components/AircraftSection/index.tsx
> +        if (!isDownloading && installStatus != InstallStatus.DownloadPrep) {
```suggestion
        if (!isDownloading && installStatus !== InstallStatus.DownloadPrep) {
```

2021-03-09 09:53 UTC, nistei approved these changes

2021-03-09 09:53 UTC, merged