feat: show taskbar progress bar during installation
flybywiresim/installer pull request #319
Opened 2021-11-13 03:14 UTC by ErickSharp

## Summary of Changes

Shows a taskbar progress bar during installation.

## Screenshots (if necessary)

![image](https://user-images.githubusercontent.com/30361843/141603770-3ffbea75-2ce5-4a09-9a5e-f11514c28c37.png)
![image](https://user-images.githubusercontent.com/30361843/141603774-ec3bf9b7-552f-4a79-a83d-bb45d0c113e0.png)

## Additional context

Discord username (if different from GitHub):

2021-11-13 17:03 UTC, FoxtrotSierra6829 requested changes

2021-11-13 17:03 UTC, FoxtrotSierra6829 commented on src/renderer/components/AircraftSection/index.tsx
> +            console.log(download.progress);
please wrap this console log into some context.

2021-11-13 17:04 UTC, FoxtrotSierra6829 commented
Also please add a changelog entry, as this is something which is noticeable to the user

2021-11-13 21:32 UTC, ErickSharp commented
> Also please add a changelog entry, as this is something which is noticeable to the user

You want me to edit the changelog.md file in the .github directory, correct? Just double checking as it seems there aren't many entries.

2021-11-14 16:04 UTC, FoxtrotSierra6829 commented
> 
> 
> > Also please add a changelog entry, as this is something which is noticeable to the user
> 
> You want me to edit the changelog.md file in the .github directory, correct? Just double checking as it seems there aren't many entries.

Yes

2021-11-15 21:40 UTC, FoxtrotSierra6829 approved these changes

2021-11-15 21:41 UTC, merged