feat: add version history
flybywiresim/installer pull request #34
Opened 2020-12-25 05:43 UTC by Benjozork

Fixes part of #25

## Summary of Changes

* Adds "Version history" section to aircraft page

## Screenshots (if necessary)

![image](https://user-images.githubusercontent.com/4503241/103121444-252a8580-464a-11eb-9280-0ac218f8b1c9.png)

## Additional context

Figma

![image](https://user-images.githubusercontent.com/4503241/103121449-2eb3ed80-464a-11eb-85ee-2cd2c848e9c5.png)

Discord username (if different from GitHub):

2020-12-25 05:49 UTC, ZigTag requested changes

2020-12-25 05:49 UTC, ZigTag commented on src/renderer/components/App/GitHubApi.ts
> +                type: 'minor'
could probably implement a detection system if PATCH >= 1 or MINOR >= 1

2020-12-25 22:28 UTC, Benjozork commented on src/renderer/components/App/GitHubApi.ts
> +                type: 'minor'
Done

2020-12-26 06:00 UTC, ZigTag requested changes

2020-12-26 06:03 UTC, ZigTag commented on src/renderer/components/AircraftSection/VersionHistory.tsx
> +type VersionProps = { index: number, className?: string, version: ModVersion };
Add newlines

2020-12-26 06:04 UTC, Benjozork commented on src/renderer/components/AircraftSection/VersionHistory.tsx
> +type VersionProps = { index: number, className?: string, version: ModVersion };
bruh

2020-12-26 06:44 UTC, merged

2020-12-26 12:04 UTC, ilyeshammadi commented
I'm a bit late to the review but here is mine:
- VersionHistroy.tsx should be `components/VersionHistroy` with `index.tsx` and `styles.tsx` 
- The component is missing a loading state while the data is being fetched.
- Font-size of the version is a bit big in my opinion

2020-12-26 12:08 UTC, ilyeshammadi commented on src/renderer/components/AircraftSection/VersionHistory.tsx
> +export const Version = styled(VersionBase)`
**nitpick:** styles should be in `VersionHistroy/styles.tsx`

2020-12-26 12:08 UTC, ilyeshammadi commented on src/renderer/components/AircraftSection/VersionHistory.tsx
> +  --timeline-node-color: ${props => props.index === 0 ? 'white' : '#757575'};
**suggestion:** Ant design has already a timeline component if you are not aware of that
https://ant.design/components/timeline/

2020-12-26 12:08 UTC, ilyeshammadi commented on src/renderer/components/AircraftSection/VersionHistory.tsx
> +const GITHUB_RELEASE_BASE_URL = 'https://github.com/flybywiresim/a32nx/releases/tag/';
**suggestion:** It's better to keep constants in a separate file at the root level.

2020-12-28 07:54 UTC, St54Kevin commented
Maybe make the current build number a different color like orange, when the installed build ist not the actual current one? And make it green when installed?