feat: addon-specific property editing
flybywiresim/installer pull request #355
Opened 2022-03-26 19:54 UTC by ErickSharp

## Summary of Changes

Creates a properties panel to allow users to edit properties that are related to a specific addon. 

## Screenshots (if necessary)

![image](https://user-images.githubusercontent.com/30361843/160255082-d5a30496-b9f0-460b-847a-c98c71b74806.png)
![image](https://user-images.githubusercontent.com/30361843/160255088-68803730-cef0-4e21-a507-e7be06432018.png)

## Additional context

Discord username (if different from GitHub):

2022-03-27 22:56 UTC, GhostEagle68 commented
Wouldn't it look better to have save and discard at the bottom?

2022-04-02 18:35 UTC, FoxtrotSierra6829 requested changes

2022-04-02 18:35 UTC, FoxtrotSierra6829 commented on src/renderer/components/AircraftSection/Properties/index.tsx
> +import { Link, useParams } from 'react-router-dom';
2:10  error  'Link' is defined but never used       @typescript-eslint/no-unused-vars

2022-04-02 18:35 UTC, FoxtrotSierra6829 commented on src/renderer/components/AircraftSection/Properties/index.tsx
> +import { ArrowLeft } from 'react-bootstrap-icons';
8:10  error  'ArrowLeft' is defined but never used  @typescript-eslint/no-unused-vars

2022-04-02 18:43 UTC, FoxtrotSierra6829 commented on src/renderer/components/Modal/index.tsx
> +    bodyText?: string;
Why should this be optional?

2022-04-02 19:02 UTC, FoxtrotSierra6829 commented
![grafik](https://user-images.githubusercontent.com/50082450/161397587-ecc87536-084b-417d-bb16-d9d1c2118977.png)
Buttons don't match the other button's design theme

2022-04-15 16:51 UTC, closed without merging