Checks if msfs is open, also made download bar smoother
flybywiresim/installer pull request #38
Opened 2020-12-31 05:50 UTC by ZigTag

Fixes #13 

## Summary of Changes

I added a install button which says "Please Close MSFS" 
also made the install bar smoother.

## Screenshots (if necessary)

## Additional context

Discord username (if different from GitHub):

2021-01-03 03:14 UTC, Benjozork requested changes

2021-01-03 03:14 UTC, Benjozork commented on src/renderer/components/AircraftSection/index.tsx
>      []);
```suggestion
    }, []);
```

2021-01-03 03:14 UTC, Benjozork commented on src/renderer/components/AircraftSection/index.tsx
> +    async function checkIfMSFS() {
Why is this `async` ?

2021-01-03 03:14 UTC, Benjozork commented on src/renderer/components/AircraftSection/styles.tsx
> +        >Please Close MSFS</InstallButton>)``;
```suggestion
        >Please close MSFS</InstallButton>)``;
```

2021-01-08 08:22 UTC, ZigTag commented on src/renderer/components/AircraftSection/index.tsx
> +    async function checkIfMSFS() {
So it won't block the other functions

2021-01-10 01:32 UTC, Benjozork commented on src/renderer/components/AircraftSection/index.tsx
> +    async function checkIfMSFS() {
Discussed on discord

2021-01-10 01:38 UTC, nistei requested changes

2021-01-10 01:38 UTC, nistei commented on src/renderer/components/AircraftSection/index.tsx
> +    async function checkIfMSFS() {
```suggestion
    function checkIfMSFS() {
```

2021-01-10 04:55 UTC, merged