refactor: remove antd and antd icons
flybywiresim/installer pull request #452
Opened 2024-01-03 05:03 UTC by Benjozork

## Summary of Changes

- Removed `antd` and `@ant-design/icons` and their remaining usages, to save about 8MB on the final exe size and be able to upload to CF again

2024-01-06 22:17 UTC, FoxtrotSierra6829 requested changes
Font size issues in several places like settings, simbridge settings, simbridge release notes etc. Generally font sizes are observed to be smaller, buttons also affected. Please compare with latest release.

|PR| 3.3.8|
|--|--|
|![Screenshot (3448)](https://github.com/flybywiresim/installer/assets/50082450/5836f3d5-5efc-41cd-a4eb-8bba451a359c)|![Screenshot (3450)](https://github.com/flybywiresim/installer/assets/50082450/cf5d8d04-083b-4486-bf76-c1551fb94d87)|
|![Screenshot (3455)](https://github.com/flybywiresim/installer/assets/50082450/46707828-3ec7-4ca8-aee9-a5ef7a1781df)|![Screenshot (3449)](https://github.com/flybywiresim/installer/assets/50082450/a6d0b961-aa54-4e6f-8913-1cdd90125a75)|
|![Screenshot (3456)](https://github.com/flybywiresim/installer/assets/50082450/f88e1c2c-0ff4-4ee2-b96e-bc5641357110)|![Screenshot (3457)](https://github.com/flybywiresim/installer/assets/50082450/38bd93e0-b1c7-432b-b3c2-7f3e6455cb16)|

Also the full screen crash report that currently occurs on initial start when updating from the latest release to master has UI issues.

|3.3.8 -> PR| 3.3.8 -> master|
|--|--|
|![Screenshot (3453)](https://github.com/flybywiresim/installer/assets/50082450/2e22fcc3-280e-4999-b689-56a31bc45fa9)|![Screenshot (3459)](https://github.com/flybywiresim/installer/assets/50082450/cfa49ee5-82e0-4aa3-8991-60c279652741)|

Changes on InstallerUpdate LGTM and are tested by auto-updating PR -> 3.3.8. No issues observed.

2024-01-07 12:28 UTC, Benjozork commented
@FoxtrotSierra6829 I fixed the styling issues, however I could not reproduce the issue coming from latest release

2024-01-17 11:34 UTC, FoxtrotSierra6829 commented on src/renderer/index.tsx
> +    throw new Error('a'.repeat(255));
should be removed

2024-01-30 19:28 UTC, Benjozork commented on src/renderer/index.tsx
> +    throw new Error('a'.repeat(255));
lol, yeah, probably...

2024-02-08 23:55 UTC, FoxtrotSierra6829 requested changes
Still some small issues

- _Don't show again_ (tickbox) too small in SimBridge autostart modal (can be disregarded if issue is opened to replace it with the normal _don't show again_ (toggle) version from other modals)
![Screenshot (3490)](https://github.com/flybywiresim/installer/assets/50082450/ef80828d-b736-4941-ab98-e21b55bcc74c)

- _Location for temporary folders_ path to small (visibible if option above is enabled)
![Screenshot (3492)](https://github.com/flybywiresim/installer/assets/50082450/63d9d63d-b00e-4378-98e6-f7b83bafacda)

- _Configuration download URL_ path too small

- Error code in modal spills over
![Screenshot (3493)](https://github.com/flybywiresim/installer/assets/50082450/5e206e8d-346b-4d96-870d-8f7061f428ff)

2024-02-25 21:19 UTC, frankkopp approved these changes

2024-02-25 21:32 UTC, merged