refactor: move to electron-vite for build
flybywiresim/installer pull request #462
Opened 2024-03-30 20:14 UTC by Benjozork

## Summary of Changes

- Entirely replaces webpack with electron-vite

2024-04-14 21:47 UTC, brewers10 commented
Quality Assurance Tester Report

Discord: brewers_10
Object of testing: #462 
Tier of Testing: 1
Date: 14/04/2024

Testing Process: 
Installed installer
Installed stable versions of A32NX, B74S, KFBW and Simbridge. Simbridge loads perfectly fine and aircraft/scenery work with sim.

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

Media:
N/A

2024-04-14 22:36 UTC, alepouna requested changes

2024-04-14 22:36 UTC, alepouna commented on src/renderer/index.tsx
> +console.log('a');
```suggestion

```
Debug log?

2024-04-23 11:09 UTC, alepouna commented
Quality Assurance Tester Report

Discord: alepouna
Object of testing: #462
Date: 23/04/2024

Testing Process:
- Installed installer

Negatives:
Descriptions are missing from addons, 'Error' when hovering on already installed items.
![image](https://github.com/flybywiresim/installer/assets/98479040/e164d8e3-9b7a-49d6-8a13-fc8e1c820442)

Testing Results:
Not Passed

Console logs:
Spam of Sentry errors such as
> index-CbxzvBJf.js:7930 Fetch API cannot load sentry-ipc://sentry-electron.scope/sentry_key. URL scheme "sentry-ipc" is not supported.
> index-CbxzvBJf.js:7649 Sentry SDK failed to establish connection with the Electron main process.
  - Ensure you have initialized the SDK in the main process
  - If your renderers use custom sessions, be sure to set 'getSessions' in the main process options
  - If you are bundling your main process code and using Electron < v5, you'll need to manually configure a preload script
 
No other error logs.

2024-04-24 20:02 UTC, noonebling commented
Quality Assurance Trainee Report

Discord          : noonebling
Object of testing: #462 
Tier of Testing  : 1
Date             : 24/04/2024

Testing Process: 
Installed Installer.
Installed different versions of addons in the installer

Negatives:
Descriptions are missing in all addons
![image](https://github.com/flybywiresim/installer/assets/53574110/1ea4a14e-c764-40a7-915f-c667d3373289)

The slider bars in Settings page do not change appearance when kept to the right (On position)
![image](https://github.com/flybywiresim/installer/assets/53574110/dca8785d-378c-422d-b8a9-29fd0c2ca428)


Testing Results: 
Not Passed

2024-04-28 00:05 UTC, alepouna commented
Quality Assurance Tester Report

Discord: alepouna
Object of testing: #462
Date: 27/04/2024

Testing Process:
- Installed installer 
- Test various addons and updating
- Test custom configs 


Testing Results:
Passed

2024-04-28 21:05 UTC, Popespice commented
Quality Assurance Tester Report

Discord          : Popespice
Object of testing: #462 
Tier of Testing  : 1
Date             : 28/4/2024

Testing Process: 
1. Deleted Appdata existing installer and supporting folder
2. Installed new installer from PR build
3. Opened Installer
4. Navigate to Settings
5. Click "third party licenses"
6. Observe popup that states "requested file not found"

Negatives:       
(Any issues, doubts. - type N/A if none are found)

Testing Results: 
Not Passed

Conclusions: 
Not working as expected

Media:       
Quality Assurance Tester/Trainee Report

Discord          : (name#1234)
Object of testing: (#PR Number)
Tier of Testing  : (1/2)
Date             : (DD/MM/YYYY)

Testing Process: 
(Detail is needed)

Negatives:       
(Any issues, doubts. - type N/A if none are found)

Testing Results: 
(Passed/Not Passed)

Conclusions: 
(Notes made, the positives in the PR, and anything extra you would like 
to mention - Delete Line if Nothing Extra is to be mentioned)

Media:
N/A

2024-08-18 16:49 UTC, alepouna approved these changes

2024-08-18 20:00 UTC, FoxtrotSierra6829 commented on src/renderer/utils/Directories.ts
> +    return path.join(Directories.localAppData(), MSFS_STEAM_PATH, this.sanitize(targetDir));
Steam installs into in AppData/Roaming/

2024-08-21 21:11 UTC, Benjozork commented on src/renderer/utils/Directories.ts
> +    return path.join(Directories.localAppData(), MSFS_STEAM_PATH, this.sanitize(targetDir));
Oops

2024-08-21 21:14 UTC, alepouna commented
Quality Assurance Tester Report

Discord: alepouna
Object of testing: #462
Date: 22/08/2024

Testing Process:
- Installed installer 
- Test install various addons (A32NX, big bertha, FSLTL, Salty) and updating. Test CDN and direct.
- Test custom configs 
- Check 3rd party licenses page loads fine

Testing Results:
Passed

2024-08-21 22:13 UTC, Benjozork commented on src/renderer/utils/Directories.ts
> +    return path.join(Directories.localAppData(), MSFS_STEAM_PATH, this.sanitize(targetDir));
Fixed

2024-08-21 22:17 UTC, merged